basePath: /
definitions:
  controllers.TransactionInput:
    properties:
      details:
        items:
          $ref: '#/definitions/models.TransactionDetail'
        type: array
      total_amount:
        type: integer
    type: object
  models.PaymentMethod:
    properties:
      id:
        type: integer
      is_active:
        type: boolean
      name:
        type: string
    type: object
  models.Product:
    properties:
      category_id:
        type: integer
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      stock:
        type: integer
    type: object
  models.Transaction:
    properties:
      details:
        items:
          $ref: '#/definitions/models.TransactionDetail'
        type: array
      id:
        type: integer
      total_amount:
        type: integer
      transaction_date:
        type: string
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: integer
    type: object
  models.TransactionDetail:
    properties:
      id:
        type: integer
      product_id:
        type: integer
      quantity:
        type: integer
      subtotal:
        type: integer
      transaction_id:
        type: integer
    type: object
  models.User:
    properties:
      id:
        type: integer
      password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Ini adalah dokumentasi API untuk Kasir-Go.
  title: Kasir-Go API
  version: "1.0"
paths:
  /api/admin/users:
    get:
      description: Get list of users (Admin only)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: Get all users
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create a new cashier user (Admin only)
      parameters:
      - description: User Data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Create new user
      tags:
      - User
  /api/admin/users/{id}:
    delete:
      description: Delete user (Admin only)
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Delete user
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update user data (Admin only)
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User Data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Update user
      tags:
      - User
  /api/login:
    post:
      consumes:
      - application/json
      description: Login and generate JWT token
      parameters:
      - description: Login Data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
      summary: Login user
      tags:
      - Auth
  /api/payments:
    get:
      description: Get a list of all payment methods
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.PaymentMethod'
            type: array
      summary: Get all payment methods
      tags:
      - Payment
    post:
      consumes:
      - application/json
      description: Create a new payment method
      parameters:
      - description: Payment Method
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.PaymentMethod'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaymentMethod'
      summary: Create payment method
      tags:
      - Payment
  /api/payments/{id}:
    delete:
      description: Delete a payment method by ID
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Delete payment method
      tags:
      - Payment
    put:
      consumes:
      - application/json
      description: Update an existing payment method
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: integer
      - description: Payment Method
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.PaymentMethod'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaymentMethod'
        "404":
          description: Not Found
          schema:
            type: object
      summary: Update payment method
      tags:
      - Payment
  /api/products:
    get:
      description: Get a list of all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
      summary: Get all products
      tags:
      - Product
    post:
      consumes:
      - application/json
      description: Create a new product
      parameters:
      - description: Product Data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
      summary: Create a new product
      tags:
      - Product
  /api/products/{id}:
    delete:
      description: Delete a product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Delete product
      tags:
      - Product
    put:
      consumes:
      - application/json
      description: Update an existing product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product Data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "404":
          description: Not Found
          schema:
            type: object
      summary: Update product
      tags:
      - Product
  /api/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User Data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
      summary: Register new user
      tags:
      - Auth
  /api/transactions:
    get:
      description: Get list of transactions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Transaction'
            type: array
      summary: Get transaction history
      tags:
      - Transaction
    post:
      consumes:
      - application/json
      description: Create a new transaction with details
      parameters:
      - description: Transaction Data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.TransactionInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Create new transaction
      tags:
      - Transaction
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
